### PR TITLE
link checking exceptions

### PR DESCRIPTION
**Pull request by asylumcs**
Previously the external link checked triggered on any external link. For pphtml users who work on entire posted eBooks, links in the PG header and footer always triggered a link report. These modifications ignore known links in PG boilerplate, reporting only unexpected external links. This is important to the errata team at PG.

### CODE REVIEW

**Review by windymilla — APPROVED** [review]
Looks fine to me, as far as my python knowledge extends

**Review by srjfoo — APPROVED** [review]
I agree with Nigel. I'm not adept at reading python, but it looks okay.

One question, though -- this will allow ebooks to cross-link to each other, but just not external links?

**Comment by asylumcs** [comment]
"One question, though -- this will allow ebooks to cross-link to each other, but just not external links?" The pphtml doesn't allow or disallow anything; it only reports. It will report cross links. It's up to the producer to decide if they are correct and allowed. I'm not sure what the policy is, but given so much of our consumables are Epubs and not HTML in a browser, I would expect very few people to include cross links that would be broken in an Epub. However as I said, pphtml doesn't enforce anything.

The main audience for this mod are those that use it on compete PG HTML files. Previously, every single one reported "external links present, not followed" even though they were almost always coming from the PG boilerplate. But not always. It made the errata team member have to go in and check all the links. Now if it reports a link, it will be one worth checking.

**Comment by cpeel** [comment]
I've pushed out this update to TEST and PROD. I defer to @asylumcs if and how this should be announced.

**Pull request merged**
