### PR TITLE
Move globals to class, fix most obvious lint issues/suggestions.

### PR DESCRIPTION
**Pull request by rtonsing**
No functional change.

### CODE REVIEW

**Review by cpeel — APPROVED** [review]
Your changes look good to me (I didn't actually test the code though).

Are you using a specific formatter to ensure a consistent style? It doesn't look like [black](https://github.com/psf/black). I can get a Github Actions workflow set up for the repo to ensure PRs pass the formatting & pylint if that helps.

**Comment by rtonsing** [comment]
I use PyCharm. It still reports 150 "problems" (warnings), many of them from pylint, so it wouldn't be good to make it a requirement yet.

Haven't used black before, but it looks good. I'll keep trying it out.

**Comment by asylumcs** [comment]
I studied all the changed code. I learned a lot. I need to look into pycharm, apparently, for my new projects. This all looks good to me if indeed there were no user-visible changes. I'm not sure where the "approve" button is, though.

**Review by srjfoo — APPROVED** [review]

**Comment by cpeel** [comment]
> I studied all the changed code. I learned a lot. I need to look into pycharm, apparently, for my new projects. This all looks good to me if indeed there were no user-visible changes. I'm not sure where the "approve" button is, though.

To signal an Approval (or request changes) in Github you go to the 'Files' view of a PR, in this case https://github.com/DistributedProofreaders/pphtml/pull/12/files, and click on the 'Review change' button on the top right.

**Comment by cpeel** [comment]
I love how prescriptive code formatters take the code style question out of the picture and lets devs (and reviewers) focus on the code. It's one of the reasons why we've standardized on one for the [dproofreaders code](https://github.com/DistributedProofreaders/dproofreaders/blob/master/SETUP/CODE_STYLE.md) as well as the [guiguts code](https://github.com/DistributedProofreaders/guiguts#code-style). I mostly don't care *which* formatter we use but if we can agree, and enforce, one that would make my developer heart very happy.

> I use PyCharm. It still reports 150 "problems" (warnings), many of them from pylint, so it wouldn't be good to make it a requirement yet.

Not sure how we can integrate PyCharm's formatting style into Github actions, but I can look into it.

> Haven't used black before, but it looks good. I'll keep trying it out.

We've used `black` at my current and prior jobs. As it says, it is Very Opinionated on its formatting (allowing very few configurable options).

**Pull request merged**
