### PR TITLE
Implement new PG HTML <title> field format

### PR DESCRIPTION
**Pull request by rtonsing**
To test, remove title or leave out "Gutenberg".

### CODE REVIEW

**Review by windymilla — CHANGES_REQUESTED** [review]
I think it should do a slightly stronger check as the current code would allow through the old format. 
Maybe at line 750, something like 
`if not t3.endswith(" | Project Gutenberg"):`
You also wouldn't need the check below for the title ending with a full stop.

**Comment by windymilla** [comment]
@cpeel Making this live at ppwb should probably be done after (not before) forum/news announcements of the change by Linda or people will get the warning and not know why

**Comment by rtonsing** [comment]
Could we push this to the test site to try out? And the previous version to PROD?

**Comment by cpeel** [comment]
TEST And PROD are now running the latest ppwb, ppcomp, pphtml, and pptext. After this gets merged in I'm happy to push it out to TEST.

**Review by cpeel — APPROVED** [review]

**Comment by cpeel** [comment]
TEST is now running the code from this PR.

**Pull request merged**
