### PR TITLE
ignore x-ebookmaker-drop

### PR DESCRIPTION
**Pull request by rtonsing**
This is a class name used for special handling by ebookmaker. See DP [Mobile Formats](https://www.pgdp.net/wiki/DP_Official_Documentation:PP_and_PPV/DP_HTML_Best_Practices/Introductory_Topics/Mobile_Formats). It is confusing to users to report it as a warning. See also Guiguts PR #1061.

### CODE REVIEW

**Comment by cpeel** [comment]
@rtonsing - can you please update the PR description on why we want to ignore this? The code does what it says on the tin but knowing why we want to do something is often as important as doing it.

**Review by cpeel — APPROVED** [review]

**Comment by srjfoo** [comment]
Is there a sandbox to test in?

**Comment by rtonsing** [comment]
It is on https://www.pgdp.org/~pterodactyl/ppwb/, feel free to push to the test site if you wish.

**Comment by srjfoo** [comment]
> It is on https://www.pgdp.org/~pterodactyl/ppwb/, feel free to push to the test site if you wish.

Thanks -- I tested it with the same file that I tested Nigel's update to GG -- `x-ebookmaker-drop` does not have a warning generated, but `x-ebookmaker-important` gets a "defined but not used" warning. (Note that I have no idea whether or not this is something that needs to be "fixed".

**Comment by rtonsing** [comment]
I haven't seen that one, it is not in the Wiki. But it looks like Nigel's update ignores anything beginning with `x-ebookmaker`, I'll change pphtml to do the same.

**Comment by windymilla** [comment]
It was actually [mentioned briefly in the wiki](https://www.pgdp.net/wiki/PPTools/EBookMaker#It_converts_elements_with_special_CSS_classes). I have expanded the information on that page, and also described it in the [relevant part of the Best Practices documentation](https://www.pgdp.net/wiki/DP_Official_Documentation:PP_and_PPV/DP_HTML_Best_Practices/Introductory_Topics/Mobile_Formats#It_converts_elements_with_special_CSS_classes).

**Comment by rtonsing** [comment]
Pushed change to ignore any class starting with 'x-ebookmaker'.

**Review by windymilla — APPROVED** [review]
Looks good to me

**Review by srjfoo — APPROVED** [review]

**Pull request merged**
